[2021-12-01 16:57:27,125: INFO: 01_base_model_creation]: 
********************
[2021-12-01 16:57:27,125: INFO: 01_base_model_creation]: >>>>> stage Creating Base Model started <<<<<
[2021-12-01 16:57:27,127: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-12-01 16:57:32,898: ERROR: 01_base_model_creation]: Unknown optimizer: tf.keras.optimiser.SGD(learning_rate=1e-3). Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 52, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 41, in main
    model = create_model(LOSS_FUNCTION, OPTIMIZER, METRICS, NUM_CLASSES)
  File "f:\dlcvnlp\projects\github\transfer_learning_mnist\src\utils\model.py", line 21, in create_model
    metrics=METRICS)
  File "F:\DLCVNLP\Projects\Github\Transfer_Learning_MNIST\env\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "F:\DLCVNLP\Projects\Github\Transfer_Learning_MNIST\env\lib\site-packages\keras\utils\generic_utils.py", line 562, in class_and_config_for_serialized_keras_object
    f'Unknown {printable_module_name}: {class_name}. Please ensure this '
ValueError: Unknown optimizer: tf.keras.optimiser.SGD(learning_rate=1e-3). Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
[2021-12-01 16:57:53,149: INFO: 01_base_model_creation]: 
********************
[2021-12-01 16:57:53,150: INFO: 01_base_model_creation]: >>>>> stage Creating Base Model started <<<<<
[2021-12-01 16:57:53,151: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-12-01 16:57:54,312: ERROR: 01_base_model_creation]: Unknown optimizer: tf.keras.optimisers.SGD(learning_rate=1e-3). Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 52, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 41, in main
    model = create_model(LOSS_FUNCTION, OPTIMIZER, METRICS, NUM_CLASSES)
  File "f:\dlcvnlp\projects\github\transfer_learning_mnist\src\utils\model.py", line 21, in create_model
    metrics=METRICS)
  File "F:\DLCVNLP\Projects\Github\Transfer_Learning_MNIST\env\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "F:\DLCVNLP\Projects\Github\Transfer_Learning_MNIST\env\lib\site-packages\keras\utils\generic_utils.py", line 562, in class_and_config_for_serialized_keras_object
    f'Unknown {printable_module_name}: {class_name}. Please ensure this '
ValueError: Unknown optimizer: tf.keras.optimisers.SGD(learning_rate=1e-3). Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
[2021-12-01 16:58:26,233: INFO: 01_base_model_creation]: 
********************
[2021-12-01 16:58:26,233: INFO: 01_base_model_creation]: >>>>> stage Creating Base Model started <<<<<
[2021-12-01 16:58:26,235: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-12-01 16:58:27,534: ERROR: 01_base_model_creation]: Unknown optimizer: tf.keras.optimizers.SGD(learning_rate=1e-3). Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 52, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 41, in main
    model = create_model(LOSS_FUNCTION, OPTIMIZER, METRICS, NUM_CLASSES)
  File "f:\dlcvnlp\projects\github\transfer_learning_mnist\src\utils\model.py", line 21, in create_model
    metrics=METRICS)
  File "F:\DLCVNLP\Projects\Github\Transfer_Learning_MNIST\env\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "F:\DLCVNLP\Projects\Github\Transfer_Learning_MNIST\env\lib\site-packages\keras\utils\generic_utils.py", line 562, in class_and_config_for_serialized_keras_object
    f'Unknown {printable_module_name}: {class_name}. Please ensure this '
ValueError: Unknown optimizer: tf.keras.optimizers.SGD(learning_rate=1e-3). Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
[2021-12-01 17:00:47,349: INFO: 01_base_model_creation]: 
********************
[2021-12-01 17:00:47,349: INFO: 01_base_model_creation]: >>>>> stage Creating Base Model started <<<<<
[2021-12-01 17:00:47,351: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-12-01 17:00:48,652: ERROR: 01_base_model_creation]: Unknown optimizer: tf.keras.optimizers.SGD(learning_rate=0.01). Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 51, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 40, in main
    model = create_model(LOSS_FUNCTION, OPTIMIZER, METRICS, NUM_CLASSES)
  File "f:\dlcvnlp\projects\github\transfer_learning_mnist\src\utils\model.py", line 21, in create_model
    metrics=METRICS)
  File "F:\DLCVNLP\Projects\Github\Transfer_Learning_MNIST\env\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "F:\DLCVNLP\Projects\Github\Transfer_Learning_MNIST\env\lib\site-packages\keras\utils\generic_utils.py", line 562, in class_and_config_for_serialized_keras_object
    f'Unknown {printable_module_name}: {class_name}. Please ensure this '
ValueError: Unknown optimizer: tf.keras.optimizers.SGD(learning_rate=0.01). Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
[2021-12-01 17:01:08,859: INFO: 01_base_model_creation]: 
********************
[2021-12-01 17:01:08,859: INFO: 01_base_model_creation]: >>>>> stage Creating Base Model started <<<<<
[2021-12-01 17:01:08,860: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-12-01 17:01:10,178: INFO: 01_base_model_creation]: >>>>> stage Creating Base Model completed!<<<<<

